// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firkhraag/product-api/sdk/models"
)

// AddProductReader is a Reader for the AddProduct structure.
type AddProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddProductBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewAddProductUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddProductOK creates a AddProductOK with default headers values
func NewAddProductOK() *AddProductOK {
	return &AddProductOK{}
}

/*AddProductOK handles this case with default header values.

This API endpoint returns no content
*/
type AddProductOK struct {
}

func (o *AddProductOK) Error() string {
	return fmt.Sprintf("[POST /products][%d] addProductOK ", 200)
}

func (o *AddProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddProductBadRequest creates a AddProductBadRequest with default headers values
func NewAddProductBadRequest() *AddProductBadRequest {
	return &AddProductBadRequest{}
}

/*AddProductBadRequest handles this case with default header values.

Validation errors defined as an array of strings
*/
type AddProductBadRequest struct {
	Payload *models.ValidationError
}

func (o *AddProductBadRequest) Error() string {
	return fmt.Sprintf("[POST /products][%d] addProductBadRequest  %+v", 400, o.Payload)
}

func (o *AddProductBadRequest) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *AddProductBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddProductUnprocessableEntity creates a AddProductUnprocessableEntity with default headers values
func NewAddProductUnprocessableEntity() *AddProductUnprocessableEntity {
	return &AddProductUnprocessableEntity{}
}

/*AddProductUnprocessableEntity handles this case with default header values.

Generic error message returned as a string
*/
type AddProductUnprocessableEntity struct {
	Payload *models.GenericError
}

func (o *AddProductUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /products][%d] addProductUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *AddProductUnprocessableEntity) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *AddProductUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
